Add init script commands to manage-iocs
install [ioc] - creates/updates stub init script
enable [ioc]  - Calls update-rc.d to add to boot order
disable [ioc] - Calls update-rc.d to remove from boot order

diff --git a/manage-iocs b/manage-iocs
--- a/manage-iocs
+++ b/manage-iocs
@@ -2,22 +2,31 @@
 
 CONF=/etc/default/epics-softioc
 
+LIBRARY=/usr/share/sysv-rc-softioc/library.sh
+INITBASESCRIPT=/usr/share/sysv-rc-softioc/softioc
+INITDDIR=/etc/init.d
+
 warn () {
-	echo "Warning: $1" >&2
+	echo "$1" >&2
 }
 
 die () {
-	echo "Error: $1" >&2
-	usage
+	echo "$1" >&2
+	exit 1
 }
+
+. "$LIBRARY"
 
 usage() {
 	printf "Usage: %s [-v] [-x] cmd\n" `basename $0`
 	echo "Available commands:"
-	echo "  help         - display this message"
-	echo "  report [ioc] - Show config of all/an IOC"
-	echo "  status       - Check if IOCs are running"
-	echo "  nextport     - Find the next unused procServ port"
+	echo "  help          - display this message"
+	echo "  report [ioc]  - Show config of all/an IOC"
+	echo "  status        - Check if IOCs are running"
+	echo "  nextport      - Find the next unused procServ port"
+	echo "  install [ioc] - Create /etc/init.d/softioc-[ioc]"
+	echo "  enable [ioc]  - Register IOC to start during system boot"
+	echo "  disable [ioc] - Un-register IOC"
 	exit 2
 }
 
@@ -45,30 +54,48 @@ reportone() {
 	echo -e "$BASE\t$IOC\t\t$USER\t\t$PORT\t$HOST\t$EXEC"
 }
 
-#   Run command $1 on IOC instances
-# $1 - A shell command
-# $2 - IOC name (empty for all IOCs)
-visit() {
-	[ -z "$1" ] && die "visitall: missing argument"
+installioc() {
+	IOC="$1"
+	BASE="`findbase "$IOC"`"
+	[ $? -ne 0 ] && die "Failed to find ioc $IOC"
+	echo "Installing IOC $BASE/$IOC"
+	SCRIPT="$INITDDIR/softioc-$IOC"
+	echo "As $SCRIPT"
+	if [ -f "$SCRIPT" ] && ! grep 'AUTOMATICALLYGENERATED' "$SCRIPT" &>/dev/null
+	then
+		# script is a file and isn't automatically managed
+		mv --backup=numbered "$SCRIPT" "$SCRIPT".old || die "failed to backup existing script"
+		echo "Backing up existing script"
+	elif [ -h "$SCRIPT" ]
+	then
+		# old-style symlink
+		echo "Replacing existing symlink to `readlink "$SCRIPT"`"
+		rm -f "$SCRIPT" || die "Failed to remove symlink"
+	fi
+	cat << EOF > "$SCRIPT"
+## Notice
+# This file was generated by `basename $0`
+# on `date -R`
+# If you edit this file then remove the following line
+# to prevent automatic updates
+## AUTOMATICALLYGENERATED
 
-	save_IFS="$IFS"
-	IFS=':'
-	for ent in $IOCPATH
-	do
-		IFS="$save_IFS"
-		[ -z "$ent" ] && continue
+### BEGIN INIT INFO
+# Provides:          softioc-$IOC
+# Required-Start:    \$remote_fs \$local_fs \$network \$syslog \$time
+# Required-Stop:     \$remote_fs \$local_fs \$network \$syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: An EPICS Soft IOC
+# Description:       Control a single software IOC
+### END INIT INFO
 
-		for iocconf in "$ent"/*/config
-		do
-			ioc="`dirname "$iocconf"`"
-			name="`basename "$ioc"`"
-			[ "$name" = '*' ] && continue
-
-			if [ -z "$2" -o "$name" = "$2" ]; then
-				$1 $ioc
-			fi
-		done
-	done
+. "$INITBASESCRIPT"
+EOF
+	[ -f "$SCRIPT" -a -s "$SCRIPT" ] || die "Failed to create $SCRIPT"
+	echo "Complete"
+	echo "To add the IOC to the system boot order run:"
+	echo "$0 enable $IOC"
 }
 
 VERB=
@@ -83,22 +110,7 @@ do
 done
 shift $(($OPTIND - 1))
 
-if [ -r "$CONF" ]
-then
-  . $CONF
-  [ -z "$SOFTBASE" ] && warn "SOFTBASE not set in $CONF"
-  [ -d "$SOFTBASE" ] || warn "SOFTBASE ($SOFTBASE) is not a directory"
-elif [ -n "$VERB" ]
-then
-  warn "global config '$CONF' Not found"
-fi
-
-IOCPATH=/etc/iocs
-if [ -n "$SOFTBASE" ]
-then
-  # Search in system locations first then user locations
-  IOCPATH="$IOCPATH:$SOFTBASE"
-fi
+iocinit
 
 [ -n "$VERB" ] && echo "Searching in: $IOCPATH"
 
@@ -145,6 +157,23 @@ nextport)
 	else
 		echo 4050
 	fi
+	;;
+
+install)
+	requireroot
+	installioc "$1"
+	;;
+
+enable)
+	[ -z "$1" ] && die "Missing argument"
+	echo "Enable: softioc-$1"
+	update-rc.d "softioc-$1" defaults 99
+	;;
+
+disable)
+	[ -z "$1" ] && die "Missing argument"
+	echo "Disable: softioc-$1"
+	update-rc.d -f "softioc-$1" remove
 	;;
 
 help)
